### PR TITLE
Sprint 1

### PR DESCRIPTION
**Pull request by JackOBrien**
This will make our master branch contain the code used for our Sprint 1 demo.

### CODE REVIEW

**Comment by JackOBrien** [comment]
Are we ready to merge these?

@MeganMaher @maknapp @Vi1i

**Comment by MeganMaher** [comment]
Yes.

**Comment by JackOBrien** [comment]
Should we delete the objectStreamTest branch?

**Comment by MeganMaher** [comment]
Yes.

**Pull request merged**
